USE [master]
GO
/****** Object:  Database [QLLopHoc]    Script Date: 03/10/2025 9:35:20 PM ******/
CREATE DATABASE [QLLopHoc]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLLopHoc', FILENAME = N'D:\OneDrive - lhuc202\QLLopHoc.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'QLLopHoc_log', FILENAME = N'D:\OneDrive - lhuc202\QLLopHoc_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [QLLopHoc] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLLopHoc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QLLopHoc] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QLLopHoc] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QLLopHoc] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QLLopHoc] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QLLopHoc] SET ARITHABORT OFF 
GO
ALTER DATABASE [QLLopHoc] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QLLopHoc] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QLLopHoc] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QLLopHoc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QLLopHoc] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QLLopHoc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QLLopHoc] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QLLopHoc] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QLLopHoc] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QLLopHoc] SET  DISABLE_BROKER 
GO
ALTER DATABASE [QLLopHoc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QLLopHoc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QLLopHoc] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QLLopHoc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QLLopHoc] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QLLopHoc] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QLLopHoc] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QLLopHoc] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QLLopHoc] SET  MULTI_USER 
GO
ALTER DATABASE [QLLopHoc] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QLLopHoc] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QLLopHoc] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QLLopHoc] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [QLLopHoc] SET DELAYED_DURABILITY = DISABLED 
GO
USE [QLLopHoc]
GO
/****** Object:  Table [dbo].[Class]    Script Date: 03/10/2025 9:35:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Class](
	[Id] [int] NOT NULL IDENTITY(1,1),
	[Name] [nvarchar](50) NULL,
 CONSTRAINT [PK_Class] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Student]    Script Date: 03/10/2025 9:35:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Student](
	[Id] [int] NOT NULL IDENTITY(1,1),
	[Id] [int] NOT NULL ,
	[Name] [nvarchar](50) NULL,
	[DayOfBirth] [datetime] NULL,
	[ClassId] [int] NULL,
 CONSTRAINT [PK_Student] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Student]  WITH CHECK ADD  CONSTRAINT [FK_Student_Class] FOREIGN KEY([ClassId])
REFERENCES [dbo].[Class] ([Id])
GO
ALTER TABLE [dbo].[Student] CHECK CONSTRAINT [FK_Student_Class]
GO
USE [master]
GO
ALTER DATABASE [QLLopHoc] SET  READ_WRITE 
GO
